---
title: "Double checking"
author: "Andrew Baxter"
date: "27/03/2020"
output: html_document
---

```{r setup, include=FALSE}
library(googlesheets4)
library(tidyverse)
library(knitr)

sheet <- read_sheet()

conflicts <- gs_read(sheet, ws = "conflicts_1203")
```

```{r table, echo = FALSE}
conflicts %>% 
  filter(`no mention` == 1) %>% 
  sample_n(20) %>% 
  mutate(doi = paste0("<a href='https://dx.doi.org/", doi, "' target='_blank'>", doi, "</a>"),
         PDF = paste0("<a href='", dir, "' target='_blank'>PDF</a>")) %>% 
  select(Reference, doi, PDF, title) %>% 
  mutate(done = '<input type="checkbox">') %>% 
  kable()
```

```{r contingency, eval = FALSE}
source("./R/1 - Tidying dataframe to remove duplicates.R")
conflicts %>% 
  left_join(dfe, by = "Reference") %>% 
  # clean_names() %>% 
  select(-(doi:conflicts),-(other1:year),-(nrefs.y:nr_fill)) %>% 
  pivot_longer(WHO.2014:APHA.2014, names_to = "gldoc", values_to = "cited") %>% 
  filter(cited == 1) %>%
  select(-Reference, -cited) %>% 
  pivot_longer(-gldoc, names_to = "Type of conflict", values_to = "val") %>% 
  filter(val == 1) %>%
  select(gldoc,`Type of conflict`) %>%
  table() %>% 
  addmargins() #%>% 
  # export::table2doc('outputs/conflicts_by_gl.docx', digits = 0, add.rownames = TRUE)
```

